##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.27.0] date: [Sun Jul 08 17:30:38 CST 2018]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Template


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Src/main.c \
Src/systick.c \
Src/gd32f3x0_it.c \
Firmware/CMSIS/GD/GD32F3x0/Source/system_gd32f3x0.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_adc.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_cec.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_cmp.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_crc.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_ctc.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_dac.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_dbg.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_dma.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_exti.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_fmc.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_fwdgt.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_gpio.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_i2c.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_misc.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_pmu.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_rcu.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_rtc.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_spi.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_syscfg.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_timer.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_tsi.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_usart.c \
Firmware/GD32F3x0_standard_peripheral/Source/gd32f3x0_wwdgt.c \
Utilities/gd32f3x0_eval.c

# ASM sources
ASM_SOURCES =  \
startup_gd32f3x0.s


######################################
# firmware library
######################################
PERIFLIB_SOURCES = 


#######################################
# binaries
#######################################
BINPATH = /usr/sbin
PREFIX = arm-none-eabi-
CC = $(BINPATH)/$(PREFIX)gcc
AS = $(BINPATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(BINPATH)/$(PREFIX)objcopy
AR = $(BINPATH)/$(PREFIX)ar
SZ = $(BINPATH)/$(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
# FPU = -mfpu=fpv4-sp-d16

# float-abi
# FLOAT-ABI = -mfloat-abi=hard
FLOAT-ABI = -mfloat-abi=soft

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DGD32F3X0 \
-DGD32F350


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc \
-IFirmware/CMSIS/GD/GD32F3x0/Include \
-IFirmware/CMSIS \
-IFirmware/CMSIS/GD/GD32F3x0/Source/ARM \
-IFirmware/GD32F3x0_standard_peripheral/Include \
-IUtilities


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = GD32F350CBTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

# *** EOF ***